const ListData = {
  status: 1,
  message: "All module fetched successfully",
  data: [
    {
      id: 256,
      moduleName: "Organisation",
      moduleUrl: "/organisation",
      moduleIcon: "fe fe-globe",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 256,
      children: [
        {
          id: 260,
          moduleName: "Organisation",
          moduleUrl: "/organisation/organisation",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 260,
        },
        {
          id: 261,
          moduleName: "Location",
          moduleUrl: "/organisation/location",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 261,
        },
        {
          id: 263,
          moduleName: "Financial Year",
          moduleUrl: "/organisation/financial year",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 263,
        },
        {
          id: 267,
          moduleName: "Country",
          moduleUrl: "/organisation/country",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 267,
        },
        {
          id: 293,
          moduleName: "State",
          moduleUrl: "/organisation/state",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 293,
        },
        {
          id: 359,
          moduleName: "City",
          moduleUrl: "/organisation/city",
          moduleIcon: null,
          parentModuleId: 256,
          isAuthorized: 1,
          key: 359,
        },
      ],
    },
    {
      id: 257,
      moduleName: "Authentication",
      moduleUrl: "/authentication",
      moduleIcon: "fe fe-unlock",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 257,
      children: [
        {
          id: 264,
          moduleName: "User",
          moduleUrl: "/authentication/user",
          moduleIcon: null,
          parentModuleId: 257,
          isAuthorized: 1,
          key: 264,
        },
        {
          id: 265,
          moduleName: "Group",
          moduleUrl: "/authentication/group",
          moduleIcon: null,
          parentModuleId: 257,
          isAuthorized: 1,
          key: 265,
        },
        {
          id: 289,
          moduleName: "Module",
          moduleUrl: "/authentication/module",
          moduleIcon: "fe fe-airplay",
          parentModuleId: 257,
          isAuthorized: 1,
          key: 289,
        },
      ],
    },
    {
      id: 258,
      moduleName: "Master",
      moduleUrl: "/master",
      moduleIcon: "fe fe-command",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 258,
      children: [
        {
          id: 268,
          moduleName: "Currency",
          moduleUrl: "/master/currency",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 268,
        },
        {
          id: 269,
          moduleName: "Exchange Rate",
          moduleUrl: "/master/exchange rate",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 269,
        },
        {
          id: 270,
          moduleName: "Vessel",
          moduleUrl: "/master/vessel",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 270,
        },
        {
          id: 271,
          moduleName: "IMO Category",
          moduleUrl: "/master/tank category",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 271,
        },
        {
          id: 272,
          moduleName: "Tank Type",
          moduleUrl: "/master/tank type",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 272,
        },
        {
          id: 273,
          moduleName: "Tank Status",
          moduleUrl: "/master/tank status",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 273,
        },
        {
          id: 274,
          moduleName: "Port",
          moduleUrl: "/master/port",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 274,
        },
        {
          id: 275,
          moduleName: "Tank",
          moduleUrl: "/master/tank",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 275,
        },
        {
          id: 281,
          moduleName: "Costing Head",
          moduleUrl: "/master/costing head",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 281,
        },
        {
          id: 287,
          moduleName: "Tariff Group",
          moduleUrl: "/master/tariff group",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 287,
        },
        {
          id: 329,
          moduleName: "Imdg Tcode Class",
          moduleUrl: "/master/imdg tcode class",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 329,
        },
        {
          id: 330,
          moduleName: "Tank Discharge Position",
          moduleUrl: "/master/tank discharge position",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 330,
        },
        {
          id: 331,
          moduleName: "Walkway",
          moduleUrl: "/master/walkway",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 331,
        },
        {
          id: 333,
          moduleName: "Maintenance",
          moduleUrl: "/master/maintenance",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 333,
        },
        {
          id: 338,
          moduleName: "Product Category",
          moduleUrl: "/master/product category",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 338,
        },
        {
          id: 339,
          moduleName: "Product Color",
          moduleUrl: "/master/product color",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 339,
        },
        {
          id: 340,
          moduleName: "Address Book Types",
          moduleUrl: "/master/address book types",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 340,
        },
        {
          id: 341,
          moduleName: "Address Book",
          moduleUrl: "/master/address book",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 341,
        },
        {
          id: 342,
          moduleName: "Product",
          moduleUrl: "/master/product",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 342,
        },
        {
          id: 345,
          moduleName: "Service Type",
          moduleUrl: "/master/service type",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 345,
        },
        {
          id: 346,
          moduleName: "Contract Type",
          moduleUrl: "/master/contract type",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 346,
        },
        {
          id: 356,
          moduleName: "Movement Section",
          moduleUrl: "/master/movement section",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 356,
        },
        {
          id: 363,
          moduleName: "Damage Type",
          moduleUrl: "/master/damage type",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 363,
        },
        {
          id: 364,
          moduleName: "Repair Type",
          moduleUrl: "/master/repair type",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 364,
        },
        {
          id: 365,
          moduleName: "Material",
          moduleUrl: "/master/material",
          moduleIcon: null,
          parentModuleId: 258,
          isAuthorized: 1,
          key: 365,
        },
      ],
    },
    {
      id: 259,
      moduleName: "Transaction",
      moduleUrl: "/transaction",
      moduleIcon: "fe fe-archive",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 259,
      children: [
        {
          id: 284,
          moduleName: "Enquiry",
          moduleUrl: "/transaction/enquiry",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 284,
        },
        {
          id: 291,
          moduleName: "Inventory",
          moduleUrl: "/transaction/inventory",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 291,
        },
        {
          id: 336,
          moduleName: "Insurance",
          moduleUrl: "/transaction/insurance",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 336,
        },
        {
          id: 337,
          moduleName: "Leasing Contract",
          moduleUrl: "/transaction/leasing contract",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 337,
        },
        {
          id: 344,
          moduleName: "Contract",
          moduleUrl: "/transaction/contract",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 344,
        },
        {
          id: 348,
          moduleName: "Quotation",
          moduleUrl: "/transaction/quotation",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 348,
        },
        {
          id: 350,
          moduleName: "Order",
          moduleUrl: "/transaction/order",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 350,
        },
        {
          id: 357,
          moduleName: "Vendor Invoice",
          moduleUrl: "/transaction/vendor invoice",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 357,
        },
        {
          id: 358,
          moduleName: "Maintenance and Repair",
          moduleUrl: "/transaction/maintenance and repair",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 358,
        },
        {
          id: 362,
          moduleName: "Billing",
          moduleUrl: "/transaction/billing",
          moduleIcon: null,
          parentModuleId: 259,
          isAuthorized: 1,
          key: 362,
        },
      ],
    },
    {
      id: 397,
      moduleName: "Finance",
      moduleUrl: "/finance",
      moduleIcon: "fe fe-trending-up",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 397,
      children: [
        {
          id: 398,
          moduleName: "Export Ledger",
          moduleUrl: "/finance/export ledger",
          moduleIcon: null,
          parentModuleId: 397,
          isAuthorized: 1,
          key: 398,
        },
        {
          id: 399,
          moduleName: "Export Bills",
          moduleUrl: "/finance/export bills",
          moduleIcon: null,
          parentModuleId: 397,
          isAuthorized: 1,
          key: 399,
        },
        {
          id: 400,
          moduleName: "Export Invoices",
          moduleUrl: "/finance/export invoices",
          moduleIcon: null,
          parentModuleId: 397,
          isAuthorized: 1,
          key: 400,
        },
      ],
    },
    {
      id: 401,
      moduleName: "Reports",
      moduleUrl: "/reports",
      moduleIcon: "fe fe-activity",
      parentModuleId: 0,
      isAuthorized: 1,
      key: 401,
      children: [
        {
          id: 402,
          moduleName: "Unbilled Order",
          moduleUrl: "/reports/unbilled order",
          moduleIcon: null,
          parentModuleId: 401,
          isAuthorized: 1,
          key: 402,
        },
      ],
    },
  ],
};

export default ListData.data;
